apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    components: mongodb
    project: roboshop
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      components: mongodb
      project: roboshop
      tier: database
  template:
    metadata:
      labels:
        components: mongodb
        project: roboshop
        tier: database
    spec:
      containers:
        - name: mongodb
          image: joindevops/mongodb:v1
apiVersion: v1
kind: Service 
metadata: 
  name: mongodb
  namespace: roboshop
  labels: 
    components: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    components: mongodb
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017